# Generated by Django 2.1.3 on 2020-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('lecturer', models.CharField(max_length=255)),
                ('up_date', models.DateTimeField()),
                ('file', models.FileField(upload_to='%Y/%m/%d/')),
            ],
        ),
    ]
