# Generated by Django 3.0.4 on 2020-03-19 06:33

from django.db import migrations, models
import lecture.models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('lecturer', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=lecture.models.video_upload_to)),
            ],
            options={
                'verbose_name': 'lecture',
                'verbose_name_plural': 'lecture',
                'db_table': 'dataBank_lecture',
            },
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
